name: craftcms-boilerplate
type: craftcms
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
performance_mode: mutagen
disable_upload_dirs_warning: true
additional_hostnames: 
- localhost
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment:
- CRAFT_DB_DRIVER=mysql
- CRAFT_DB_SERVER=db
- CRAFT_DB_PORT=3306
- CRAFT_DB_DATABASE=db
- CRAFT_DB_USER=db
- CRAFT_DB_PASSWORD=db

# Override the default nginx configuration
nginx_config_overrides:
- .ddev/nginx/nginx-site.conf

# Hooks - only run if files exist to avoid setup failures
hooks:
  post-start:
  - exec: "[ -f composer.json ] && composer install --no-interaction || echo 'Skipping composer install - no composer.json found'"
  - exec: "[ -f package.json ] && npm install || echo 'Skipping npm install - no package.json found'"
